services:
    counter:
        build: ./counter
        volumes:
            - ./volume:/volume
        ports:
            - 3001:3001
        environment:
            - PORT=3001

    library:
        build: ./library
        volumes:
            - ./volume:/volume
        ports:
            - 3000:3000
        environment:
            - PORT=3000
            - COUNTER_URL=counter
            - DBURL=mongodb://root:example@mongo:27017/library?authSource=admin

    mongo:
        image: mongo
        restart: always
        volumes:
            - ./volume/mongo:/data/db
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
            ME_CONFIG_BASICAUTH: false
